name: PaperChat
version: 1.0-SNAPSHOT
main: lt.domax.paperchat.PaperChat
api-version: 1.21
author: Domas Leščinskas
description: Play Minecraft and have an LLM baked right in!

commands:
  paperchat:
    description: Chat with an AI chatbot
    usage: /paperchat <question|history|clear>
    permission: paperchat.use

permissions:
  paperchat.use:
    description: Allows using the paperchat command
    default: true
